import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { KumaRegistry } from "@kuma-ui/next-plugin/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  );
}
